"""initial schema

Revision ID: 0bb3f0fa464f
Revises: 
Create Date: 2026-07-14 22:34:56.496807
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb3f0fa464f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('annual_consumption_mwh', sa.Float(), nullable=False),
    sa.Column('re_target_percent', sa.Float(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_code'), ['code'], unique=True)

    op.create_table('matching_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='matchingrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matching_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_runs_period'), ['period'], unique=False)

    op.create_table('wind_farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('operator_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('installed_capacity_mw', sa.Float(), nullable=False),
    sa.Column('commercial_operation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'UNDER_CONSTRUCTION', 'OPERATIONAL', 'DECOMMISSIONED', name='windfarmstatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wind_farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wind_farms_code'), ['code'], unique=True)

    op.create_table('consumption_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('consumed_energy_mwh', sa.Float(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumption_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumption_data_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumption_data_period_start'), ['period_start'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('wind_farm_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('contracted_energy_mwh', sa.Float(), nullable=True),
    sa.Column('contracted_percentage', sa.Float(), nullable=True),
    sa.Column('price_per_kwh', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'TERMINATED', name='contractstatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['wind_farm_id'], ['wind_farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_contract_number'), ['contract_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_wind_farm_id'), ['wind_farm_id'], unique=False)

    op.create_table('generation_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wind_farm_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_energy_mwh', sa.Float(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wind_farm_id'], ['wind_farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_data_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_data_wind_farm_id'), ['wind_farm_id'], unique=False)

    op.create_table('matching_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matching_run_id', sa.Integer(), nullable=False),
    sa.Column('wind_farm_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('allocated_energy_mwh', sa.Float(), nullable=False),
    sa.Column('customer_consumption_mwh', sa.Float(), nullable=False),
    sa.Column('achieved_re_percent', sa.Float(), nullable=False),
    sa.Column('allocation_reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['matching_run_id'], ['matching_runs.id'], ),
    sa.ForeignKeyConstraint(['wind_farm_id'], ['wind_farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matching_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_results_matching_run_id'), ['matching_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_results_period'), ['period'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_results_period'))
        batch_op.drop_index(batch_op.f('ix_matching_results_matching_run_id'))

    op.drop_table('matching_results')
    with op.batch_alter_table('generation_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_data_wind_farm_id'))
        batch_op.drop_index(batch_op.f('ix_generation_data_period_start'))

    op.drop_table('generation_data')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_wind_farm_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_contract_number'))

    op.drop_table('contracts')
    with op.batch_alter_table('consumption_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumption_data_period_start'))
        batch_op.drop_index(batch_op.f('ix_consumption_data_customer_id'))

    op.drop_table('consumption_data')
    with op.batch_alter_table('wind_farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wind_farms_code'))

    op.drop_table('wind_farms')
    with op.batch_alter_table('matching_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_runs_period'))

    op.drop_table('matching_runs')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_code'))

    op.drop_table('customers')
    # ### end Alembic commands ###
