"""add windfarm feed_in_price_per_kwh

Revision ID: 2c249216f1ac
Revises: 0bb3f0fa464f
Create Date: 2026-07-16 18:15:14.993092
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c249216f1ac'
down_revision: str | None = '0bb3f0fa464f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wind_farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_in_price_per_kwh', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wind_farms', schema=None) as batch_op:
        batch_op.drop_column('feed_in_price_per_kwh')

    # ### end Alembic commands ###
