"""add customer green target

Revision ID: fa6b9882de2c
Revises: 2c249216f1ac
Create Date: 2026-07-16 21:34:29.747755
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6b9882de2c'
down_revision: str | None = '2c249216f1ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('green_target_type', sa.Enum('RE_PERCENT', 'ENERGY', name='greentargettype'), nullable=False, server_default='RE_PERCENT'))
        batch_op.add_column(sa.Column('target_energy_mwh', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('target_energy_mwh')
        batch_op.drop_column('green_target_type')

    # ### end Alembic commands ###
